# This is an example config for train_ppo.py that can be used to run it locally.
logdir: logs_cpc_tg_lvl4
base_config: training_scripts/configs/residual_sac.gin
gin_bindings:
    max_torque: 0.1
    make_training_env.goal_difficulty: 4
    make_training_env.state_machine: '@CPCStateMachineL4'
    make_training_env.residual_state: 'GoalWithOrientState'
